import {
    USERS_PUT_REQUEST, USERS_PUT_SUCCESS, USERS_PUT_FAIL,
    put
} from "./actions/put";

import {
    USERS_REGISTER_REQUEST, USERS_REGISTER_SUCCESS, USERS_REGISTER_FAIL,
    register
} from "./actions/register";

export {
    USERS_PUT_REQUEST, USERS_PUT_SUCCESS, USERS_PUT_FAIL,
    USERS_REGISTER_REQUEST, USERS_REGISTER_SUCCESS, USERS_REGISTER_FAIL,
    put, register
};
